version: '2'
services:
    bankaudit-app:
        image: bankaudit
        external_links:
            - bankaudit-mysql:mysql
            - bankaudit-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bankaudit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    bankaudit-mysql:
        extends:
            file: mysql.yml
            service: bankaudit-mysql
    bankaudit-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bankaudit-elasticsearch
